// Generated by gencpp from file hi/hiGenSerRequest.msg
// DO NOT EDIT!


#ifndef HI_MESSAGE_HIGENSERREQUEST_H
#define HI_MESSAGE_HIGENSERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hi
{
template <class ContainerAllocator>
struct hiGenSerRequest_
{
  typedef hiGenSerRequest_<ContainerAllocator> Type;

  hiGenSerRequest_()
    {
    }
  hiGenSerRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::hi::hiGenSerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hi::hiGenSerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct hiGenSerRequest_

typedef ::hi::hiGenSerRequest_<std::allocator<void> > hiGenSerRequest;

typedef boost::shared_ptr< ::hi::hiGenSerRequest > hiGenSerRequestPtr;
typedef boost::shared_ptr< ::hi::hiGenSerRequest const> hiGenSerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hi::hiGenSerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hi::hiGenSerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hi

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hi::hiGenSerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hi::hiGenSerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hi::hiGenSerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hi::hiGenSerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hi::hiGenSerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hi::hiGenSerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hi::hiGenSerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::hi::hiGenSerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hi::hiGenSerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hi/hiGenSerRequest";
  }

  static const char* value(const ::hi::hiGenSerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hi::hiGenSerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::hi::hiGenSerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hi::hiGenSerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hiGenSerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hi::hiGenSerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::hi::hiGenSerRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // HI_MESSAGE_HIGENSERREQUEST_H
