Centauro_Hello_Pose:
  Movements: ["Move_1", "Move_2","Move_3","Move_2","Move_3","Move_2","Move_3","Move_2","Move_3"]	
  Move_1:
          JointNameMov: ["j_arm1_1","j_arm1_2","j_arm1_3","j_arm1_4","j_arm1_5","j_arm1_6","j_arm1_7"]
          PositionNameMov: [-0.0,2,1,-0.0,0.0,-0.0,0.0]
          TimeMov: [5.00,5.00,3.00,3.00,5.00,3.00,5.00]
  Move_2:
          JointNameMov: ["j_arm1_4"]
          PositionNameMov: [-1.2]
          TimeMov: [5.00]
  Move_3: 
          JointNameMov: ["j_arm1_4"]
          PositionNameMov: [-0.3]
          TimeMov: [5.00]
